#include "stm32f4xx.h"
#include "stm32f446xx.h"

void SysClockConfig (void){
	//ENABLE HSE
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));

	//POWER ENABLE CLOCK & VOLTAGE REGULATOR
	RCC->APB1ENR |=  RCC_APB1ENR_PWREN;
	PWR->CR |= 3 << PWR_CR_VOS_Pos;

	//FLASH PREFETCH
	FLASH->ACR = FLASH_ACR_PRFTEN | FLASH_ACR_ICEN | FLASH_ACR_DCEN | FLASH_ACR_LATENCY_5WS;

	//PRESCALARS HCLK, PCLK1, PCLK2
	// HB PR
	RCC->CFGR &= ~(1 << RCC_CFGR_HPRE_Pos);

	//APB1 PR
	RCC->CFGR |= (5 << RCC_CFGR_PPRE1_Pos);

	//APB2 PR
	RCC->CFGR |= (4 << RCC_CFGR_PPRE2_Pos);

	//PLL CONFIG
	RCC->PLLCFGR = (4 << RCC_PLLCFGR_PLLM_Pos) | (180 << RCC_PLLCFGR_PLLN_Pos) | (0 << RCC_PLLCFGR_PLLP_Pos) | RCC_PLLCFGR_PLLSRC; 

	//PLL ENABLE
	RCC->CR |= RCC_CR_PLLON;
	while (!(RCC->CR & RCC_CR_PLLRDY)); 

	//SELECT CLK SRC
	RCC->CFGR |= RCC_CFGR_SW_1;
	while (!(RCC->CFGR & RCC_CFGR_SWS_1));
}
